/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-04 06:32:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/header_footer/header.jsp", Long.valueOf(1667451524000L));
    _jspx_dependants.put("/header_footer/footer.jsp", Long.valueOf(1667478784930L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\n");
      out.write("    <!-- Title -->\n");
      out.write("    <title>Shinna Hotel</title>\n");
      out.write("\n");
      out.write("    <!-- Favicon -->\n");
      out.write("    <link rel=\"icon\" href=\"../image/headicon.png\">\n");
      out.write("\n");
      out.write("    <!-- Stylesheet -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"../style.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../header.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Preloader -->\n");
      out.write("    <div id=\"preloader\" style=\"background-color: #f1ebd6;\">\n");
      out.write("        <div class=\"loader\"></div>\n");
      out.write("    </div>\n");
      out.write("    <!-- /Preloader -->\n");
      out.write("\n");
      out.write("    <!-- Header Area Start -->\n");
      out.write("    <header class=\"header-area\">        \n");
      out.write("        <!-- Top Header Area Start -->\n");
      out.write("        <div class=\"top-header-area\" style=\"background-color: white;\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-6\">\n");
      out.write("                        <div class=\"top-header-content\">\n");
      out.write("                            <a href=\"#\" style=\"color: #524b42;\"><i class=\"icon_phone\" style=\"color: #f1e3c4;\"></i> <span>(02) 1234-5678</span></a>\n");
      out.write("                            <a href=\"#\" style=\"color: #524b42;\"><i class=\"icon_mail\" style=\"color: #f1e3c4;\"></i> <span>shinna@hotel.com</span></a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-6\" >\n");
      out.write("                        <div class=\"top-header-content\" >\n");
      out.write("                            <!-- Top Social Area -->\n");
      out.write("                            <div class=\"top-social-area ml-auto\">\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-facebook\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-twitter\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-tripadvisor\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-instagram\" style=\"color: #f1e3c4;\" aria-hidden=\"true\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Top Header Area End -->\n");
      out.write("\n");
      out.write("        <!-- Main Header Start -->\n");
      out.write("        <div class=\"main-header-area\">\n");
      out.write("            <div class=\"classy-nav-container breakpoint-off\" style=\"background-color: #f1e3c4;\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <!-- Classy Menu -->\n");
      out.write("                    <nav class=\"classy-navbar justify-content-between\" id=\"robertoNav\">\n");
      out.write("\n");
      out.write("                        <!-- Logo -->\n");
      out.write("                        <a class=\"nav-brand\" href=\"../login/index.jsp\"><img src=\"../image/headerlogo.png\" alt=\"\"></a>\n");
      out.write("\n");
      out.write("                        <!-- Navbar Toggler -->\n");
      out.write("                        <div class=\"classy-navbar-toggler\">\n");
      out.write("                            <span class=\"navbarToggler\"><span></span><span></span><span></span></span>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <!-- Menu -->\n");
      out.write("                        <div class=\"classy-menu\" >\n");
      out.write("                            <!-- Menu Close Button -->\n");
      out.write("                            <div class=\"classycloseIcon\">\n");
      out.write("                                <div class=\"cross-wrap\"><span class=\"top\"></span><span class=\"bottom\"></span></div>\n");
      out.write("                            </div>\n");
      out.write("                            <!-- Nav Start -->\n");
      out.write("                            <div class=\"classynav\">\n");
      out.write("                                \n");
      out.write("\n");
      out.write("                                <!-- Search -->\n");
      out.write("                                <div class=\"book-now-btn\"  >\n");
      out.write("                                   <a href=\"../room/room_all.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">객실정보</a>|                       \n");
      out.write("                                   <a href=\"../inquiry/inquiry.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">문의하기</a>|                          \n");
      out.write("                                   <a href=\"../location/location.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">위치찾기</a>|                          \n");
      out.write("                                    <a href=\"../reservation/reservation.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">예약 </a>|                              \n");
      out.write("                                    <a href=\"../login/login.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">로그인 </a>|\n");
      out.write("                                    <a href=\"../join/join.jsp\" style=\"background-color: #f1e3c4;color: #524b42;\">회원가입 </a>\n");
      out.write("                                </div>\n");
      out.write("                               \n");
      out.write("                            </div>\n");
      out.write("                            <!-- Nav End -->\n");
      out.write("                        </div>\n");
      out.write("                    </nav>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    <!-- Header Area End -->");
      out.write("\n");
      out.write("    \n");
      out.write("    <!-- Welcome Area Start -->\n");
      out.write("    <section class=\"welcome-area\">\n");
      out.write("        <div class=\"welcome-slides owl-carousel\">\n");
      out.write("            <!-- Single Welcome Slide -->\n");
      out.write("            <div class=\"single-welcome-slide bg-img bg-overlay\" style=\"background-image: url(../image/그랜드1.jpg);\" src=\"../image/그랜드1.jpg\">\n");
      out.write("                <!-- Welcome Content -->\n");
      out.write("                <div class=\"welcome-content h-100\">\n");
      out.write("                    <div class=\"container h-100\">\n");
      out.write("                        <div class=\"row h-100 align-items-center\">\n");
      out.write("                            <!-- Welcome Text -->\n");
      out.write("                            <div class=\"col-12\">\n");
      out.write("                                <div class=\"welcome-text text-center\">\n");
      out.write("                                    <h6 data-animation=\"fadeInLeft\" data-delay=\"200ms\">SHINNA HOTEL</h6>\n");
      out.write("                                    <h2 data-animation=\"fadeInLeft\" data-delay=\"500ms\">신나호텔에 오신 것을 환영합니다.</h2>\n");
      out.write("                                    <a href=\"#\" class=\"btn roberto-btn btn-2\" style=\"border: 2px solid #f1e3c4;\" data-animation=\"fadeInLeft\" data-delay=\"800ms\">예약하기</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Single Welcome Slide -->\n");
      out.write("            <div class=\"single-welcome-slide bg-img bg-overlay\" style=\"background-image: url(../image/디럭스1.jpg);\" src=\"../image/디럭스1.jpg\">\n");
      out.write("                <!-- Welcome Content -->\n");
      out.write("                <div class=\"welcome-content h-100\">\n");
      out.write("                    <div class=\"container h-100\">\n");
      out.write("                        <div class=\"row h-100 align-items-center\">\n");
      out.write("                            <!-- Welcome Text -->\n");
      out.write("                            <div class=\"col-12\">\n");
      out.write("                                <div class=\"welcome-text text-center\">\n");
      out.write("                                    <h6 data-animation=\"fadeInUp\" data-delay=\"200ms\">SHINNA HOTEL</h6>\n");
      out.write("                                    <h2 data-animation=\"fadeInUp\" data-delay=\"500ms\">신나호텔에 오신 것을 환영합니다.</h2>\n");
      out.write("                                    <a href=\"#\" class=\"btn roberto-btn btn-2\" style=\"border: 2px solid #f1e3c4;\" data-animation=\"fadeInUp\" data-delay=\"800ms\">예약하기</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Single Welcome Slide -->\n");
      out.write("            <div class=\"single-welcome-slide bg-img bg-overlay\" style=\"background-image: url(../image/스탠다드1.jpg);\" data-img-url=\"../image/스탠다드1.jpg\">\n");
      out.write("                <!-- Welcome Content -->\n");
      out.write("                <div class=\"welcome-content h-100\">\n");
      out.write("                    <div class=\"container h-100\">\n");
      out.write("                        <div class=\"row h-100 align-items-center\">\n");
      out.write("                            <!-- Welcome Text -->\n");
      out.write("                            <div class=\"col-12\">\n");
      out.write("                                <div class=\"welcome-text text-center\">\n");
      out.write("                                    <h6 data-animation=\"fadeInUp\" data-delay=\"200ms\">SHINNA HOTEL</h6>\n");
      out.write("                                    <h2 data-animation=\"fadeInUp\" data-delay=\"500ms\">신나호텔에 오신 것을 환영합니다.</h2>\n");
      out.write("                                    <a href=\"#\" class=\"btn roberto-btn btn-2\" style=\"border: 2px solid #f1e3c4;\" data-animation=\"fadeInUp\" data-delay=\"800ms\">예약하기</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <!-- Welcome Area End -->\n");
      out.write("\n");
      out.write("    <!-- About Us Area Start -->\n");
      out.write("    <section class=\"roberto-about-area section-padding-100-0\">\n");
      out.write("        <!-- Hotel Search Form Area -->\n");
      out.write("        <div class=\"hotel-search-form-area\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <div class=\"hotel-search-form\">\n");
      out.write("                    <form action=\"#\" method=\"post\">\n");
      out.write("                        <p>날짜, 인원 선택</p>\n");
      out.write("                        <div class=\"row justify-content-between align-items-end\">\n");
      out.write("                            <div class=\"col-6 col-md-2 col-lg-3\">\n");
      out.write("                                <label for=\"checkIn\">체크인</label>\n");
      out.write("                                <input type=\"date\" class=\"form-control\" id=\"checkIn\" name=\"checkin-date\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-6 col-md-2 col-lg-3\">\n");
      out.write("                                <label for=\"checkOut\">체크아웃</label>\n");
      out.write("                                <input type=\"date\" class=\"form-control\" id=\"checkOut\" name=\"checkout-date\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-4 col-md-1\">\n");
      out.write("                                <label for=\"room\">객실</label>\n");
      out.write("                                <select name=\"room\" id=\"room\" class=\"form-control\">\n");
      out.write("                                    <option value=\"01\">01</option>\n");
      out.write("                                    <option value=\"02\">02</option>\n");
      out.write("                                    <option value=\"03\">03</option>\n");
      out.write("                                    <option value=\"04\">04</option>\n");
      out.write("                                    <option value=\"05\">05</option>\n");
      out.write("                                    <option value=\"06\">06</option>\n");
      out.write("                                </select>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-4 col-md-1\">\n");
      out.write("                                <label for=\"adults\">성인</label>\n");
      out.write("                                <select name=\"adults\" id=\"adults\" class=\"form-control\">\n");
      out.write("                                    <option value=\"01\">01</option>\n");
      out.write("                                    <option value=\"02\">02</option>\n");
      out.write("                                    <option value=\"03\">03</option>\n");
      out.write("                                    <option value=\"04\">04</option>\n");
      out.write("                                    <option value=\"05\">05</option>\n");
      out.write("                                    <option value=\"06\">06</option>\n");
      out.write("                                </select>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-4 col-md-2 col-lg-1\">\n");
      out.write("                                <label for=\"children\">어린이</label>\n");
      out.write("                                <select name=\"children\" id=\"children\" class=\"form-control\">\n");
      out.write("                                    <option value=\"01\">01</option>\n");
      out.write("                                    <option value=\"02\">02</option>\n");
      out.write("                                    <option value=\"03\">03</option>\n");
      out.write("                                    <option value=\"04\">04</option>\n");
      out.write("                                    <option value=\"05\">05</option>\n");
      out.write("                                    <option value=\"06\">06</option>\n");
      out.write("                                </select>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-12 col-md-3\">\n");
      out.write("                                <button type=\"submit\" class=\"form-control btn roberto-btn w-100\" style=\"background-color: #f1e3c4;color: #524b42;\">검색</button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("           <!-- Blog Area Start -->\n");
      out.write("    <section class=\"roberto-blog-area section-padding-100-0\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <!-- Section Heading -->\n");
      out.write("                <div class=\"col-12\">\n");
      out.write("                    <div class=\"section-heading text-center wow fadeInUp\" data-wow-delay=\"100ms\">\n");
      out.write("                        <h6 style=\"color: #524b42;\">Shinna</h6>\n");
      out.write("                        <h2 style=\"color: #524b42;\">Production &amp; package</h2>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <!-- Single Post Area -->\n");
      out.write("                <div class=\"col-12 col-md-6 col-lg-4\">\n");
      out.write("                    <div class=\"single-post-area mb-100 wow fadeInUp\" data-wow-delay=\"300ms\">\n");
      out.write("                        <a href=\"#\" class=\"post-thumbnail\"><img src=\"../image/R0000001ONZJ_KR.jpg\" alt=\"\"></a>\n");
      out.write("                        <!-- Post Meta -->\n");
      out.write("                        <div class=\"post-meta\">                            \n");
      out.write("                            <a href=\"#\" class=\"post-catagory\">Event</a>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- Post Title -->\n");
      out.write("                        <a href=\"#\" class=\"post-title\">Artist of the Day</a>\n");
      out.write("                        <p>객실 1실 1박, 소마 드로잉카페 2인 이용권 1매</p>                        \n");
      out.write("                        <p>2022.09.28 ~ 2022.12.31</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Single Post Area -->\n");
      out.write("                <div class=\"col-12 col-md-6 col-lg-4\">\n");
      out.write("                    <div class=\"single-post-area mb-100 wow fadeInUp\" data-wow-delay=\"500ms\">\n");
      out.write("                        <a href=\"#\" class=\"post-thumbnail\"><img src=\"../image/R0000001PC6L_KR.jpg\" alt=\"\"></a>\n");
      out.write("                        <!-- Post Meta -->\n");
      out.write("                        <div class=\"post-meta\">                       \n");
      out.write("                            <a href=\"#\" class=\"post-catagory\">Event</a>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- Post Title -->\n");
      out.write("                        <a href=\"#\" class=\"post-title\">신나스테이에서 한 달 살기</a>\n");
      out.write("                        <p>객실 14박~30박, 쿠폰북 1권, HDMI 케이블 대여</p>\n");
      out.write("                        <p>2022.07/01 ~ 2022.12.31</p>                        \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Single Post Area -->\n");
      out.write("                <div class=\"col-12 col-md-6 col-lg-4\">\n");
      out.write("                    <div class=\"single-post-area mb-100 wow fadeInUp\" data-wow-delay=\"700ms\">\n");
      out.write("                        <a href=\"#\" class=\"post-thumbnail\"><img src=\"../image/R0000001OYLY_KR.jpg\" alt=\"\"></a>\n");
      out.write("                        <!-- Post Meta -->\n");
      out.write("                        <div class=\"post-meta\">                            \n");
      out.write("                            <a href=\"#\" class=\"post-catagory\">Event</a>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- Post Title -->\n");
      out.write("                        <a href=\"#\" class=\"post-title\">Shinna Culture Stay(뚝섬미술관)</a>\n");
      out.write("                        <p>객실 1박, 조식 2인 뚝섬미술관 '로그아웃' 전시 초대권 1매</p>\n");
      out.write("                        <p>2022.05.23 ~ 2022.12.31</p>\n");
      out.write("                   \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <!-- Blog Area End -->\n");
      out.write("\n");
      out.write("        <div class=\"container mt-100\">\n");
      out.write("            <div class=\"row align-items-center\">\n");
      out.write("                <div class=\"col-12 col-lg-6\">\n");
      out.write("                    <!-- Section Heading -->\n");
      out.write("                    <div class=\"section-heading wow fadeInUp\" data-wow-delay=\"100ms\">\n");
      out.write("                        <h6 style=\"color: #524b42;\">신나리워즈</h6>\n");
      out.write("                        <hr>\n");
      out.write("                        <h2>Welcome to <br>Shinna Hotel</h2>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"about-us-content mb-100\">\n");
      out.write("                        <h5 class=\"wow fadeInUp\" data-wow-delay=\"300ms\" style=\"color: #524b42;\">호텔설명</h5>\n");
      out.write("                        <p class=\"wow fadeInUp\" data-wow-delay=\"400ms\">Manager: <span style=\"color: #524b42;\">Shinna manager</span></p>\n");
      out.write("                        \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"col-12 col-lg-6\">\n");
      out.write("                    <div class=\"about-us-thumbnail mb-100 wow fadeInUp\" data-wow-delay=\"700ms\">\n");
      out.write("                        <div class=\"row no-gutters\">\n");
      out.write("                            <div class=\"col-6\">\n");
      out.write("                                <div class=\"single-thumb\">\n");
      out.write("                                    <img src=\"/image/그랜드1.jpg\" alt=\"\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"single-thumb\">\n");
      out.write("                                    <img src=\"/image/디럭스1.jpg\" alt=\"\">\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-6\">\n");
      out.write("                                <div class=\"single-thumb\">\n");
      out.write("                                    <img src=\"/image/스탠다드1.jpg\" alt=\"\">\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <!-- About Us Area End -->\n");
      out.write("\n");
      out.write("  \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("  \n");
      out.write(" \n");
      out.write("\n");
      out.write("    <!-- Call To Action Area Start -->\n");
      out.write("<!--     <section class=\"roberto-cta-area\"> -->\n");
      out.write("<!--         <div class=\"container\"> -->\n");
      out.write("<!--             <div class=\"cta-content bg-img bg-overlay jarallax\" style=\"background-image: url(img/bg-img/1.jpg);\"> -->\n");
      out.write("<!--                 <div class=\"row align-items-center\"> -->\n");
      out.write("<!--                     <div class=\"col-12 col-md-7\"> -->\n");
      out.write("<!--                         <div class=\"cta-text mb-50\"> -->\n");
      out.write("<!--                             <h2>Contact us now!</h2> -->\n");
      out.write("<!--                             <h6>Contact (+12) 345-678-9999 to book directly or for advice</h6> -->\n");
      out.write("<!--                         </div> -->\n");
      out.write("<!--                     </div> -->\n");
      out.write("<!--                     <div class=\"col-12 col-md-5 text-right\"> -->\n");
      out.write("<!--                         <a href=\"#\" class=\"btn roberto-btn mb-50\">Contact Now</a> -->\n");
      out.write("<!--                     </div> -->\n");
      out.write("<!--                 </div> -->\n");
      out.write("<!--             </div> -->\n");
      out.write("<!--         </div> -->\n");
      out.write("<!--     </section> -->\n");
      out.write("    <!-- Call To Action Area End -->\n");
      out.write("\n");
      out.write("    <!-- Partner Area Start -->\n");
      out.write("<!--     <div class=\"partner-area\"> -->\n");
      out.write("<!--         <div class=\"container\"> -->\n");
      out.write("<!--             <div class=\"row\"> -->\n");
      out.write("<!--                 <div class=\"col-12\"> -->\n");
      out.write("<!--                     <div class=\"partner-logo-content d-flex align-items-center justify-content-between wow fadeInUp\" data-wow-delay=\"300ms\"> -->\n");
      out.write("<!--                         <a href=\"#\" class=\"partner-logo\"><img src=\"img/core-img/p1.png\" alt=\"\"></a> -->\n");
      out.write("<!--                         <a href=\"#\" class=\"partner-logo\"><img src=\"img/core-img/p2.png\" alt=\"\"></a> -->\n");
      out.write("<!--                         <a href=\"#\" class=\"partner-logo\"><img src=\"img/core-img/p3.png\" alt=\"\"></a> -->\n");
      out.write("<!--                         <a href=\"#\" class=\"partner-logo\"><img src=\"img/core-img/p4.png\" alt=\"\"></a> -->\n");
      out.write("<!--                         <a href=\"#\" class=\"partner-logo\"><img src=\"img/core-img/p5.png\" alt=\"\"></a> -->\n");
      out.write("<!--                     </div> -->\n");
      out.write("<!--                 </div> -->\n");
      out.write("<!--             </div> -->\n");
      out.write("<!--         </div> -->\n");
      out.write("<!--     </div> -->\n");
      out.write("    <!-- Partner Area End -->\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("<!-- Footer Area Start -->\n");
      out.write("    <footer class=\"footer-area section-padding-80-0\">\n");
      out.write("        <!-- Main Footer Area -->\n");
      out.write("        <div class=\"main-footer-area\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row align-items-baseline justify-content-between\">\n");
      out.write("                    <!-- Single Footer Widget Area -->\n");
      out.write("                    <div class=\"col-12 col-sm-6 col-lg-3\">\n");
      out.write("                        <div class=\"single-footer-widget mb-80\">\n");
      out.write("                        	<a href=\"index.jsp\">\n");
      out.write("                        		<image src=\"../image/푸터.png\">\n");
      out.write("                        	</a>\n");
      out.write("<!--                             Footer Logo -->\n");
      out.write("<!--                             <a href=\"#\" class=\"footer-logo\"><img src=\"img/core-img/logo2.png\" alt=\"\"></a> -->\n");
      out.write("\n");
      out.write("<!--                             <h4>+12 345-678-9999</h4> -->\n");
      out.write("<!--                             <span>Info.colorlib@gmail.com</span> -->\n");
      out.write("<!--                             <span>856 Cordia Extension Apt. 356, Lake Deangeloburgh, South Africa</span> -->\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- Single Footer Widget Area -->\n");
      out.write("                    <div class=\"col-12 col-sm-6 col-lg-3\">\n");
      out.write("                        <div class=\"single-footer-widget mb-80\">\n");
      out.write("                            <!-- Widget Title -->\n");
      out.write("                            <h5 class=\"widget-title\" style=\"color: black; \" >신나호텔</h5>\n");
      out.write("\n");
      out.write("                            <!-- Single Blog Area -->\n");
      out.write("                            <div class=\"latest-blog-area\">\n");
      out.write("                                <a href=\"#\" class=\"post-title\">서울 강남구 테헤란로 146</a>\n");
      out.write("                                <span class=\"post-date\">역삼동 736-6</span>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Single Blog Area -->\n");
      out.write("                            <div class=\"latest-blog-area\">\n");
      out.write("                                <a href=\"#\" class=\"post-title\">02) 1234 - 5678 </a>\n");
      out.write("                                \n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- Single Footer Widget Area -->\n");
      out.write("                    <div class=\"col-12 col-sm-4 col-lg-2\">\n");
      out.write("                        <div class=\"single-footer-widget mb-80\">\n");
      out.write("                            <!-- Widget Title -->\n");
      out.write("                            <h5 class=\"widget-title\"></h5>\n");
      out.write("\n");
      out.write("                            <!-- Footer Nav -->\n");
      out.write("                            <ul class=\"footer-nav\" style=\"color: #524b42;\">\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i> 소개</a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i> 객실정보</a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i> 예약</a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i> 문의하기</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- Single Footer Widget Area -->\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Copywrite Area -->\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"copywrite-content\">\n");
      out.write("                <div class=\"row align-items-center\">\n");
      out.write("                    <div class=\"col-12 col-md-8\">\n");
      out.write("                        <!-- Copywrite Text -->\n");
      out.write("                        <div class=\"copywrite-text\">\n");
      out.write("                            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | 신라호텔 사이트를 모티브로 제작된 사이트입니다.\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-12 col-md-4\">\n");
      out.write("                        <!-- Social Info -->\n");
      out.write("                        <div class=\"social-info\">\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a>\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a>\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("    <!-- Footer Area End -->");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- **** All JS Files ***** -->\n");
      out.write("    <!-- jQuery 2.2.4 -->\n");
      out.write("    <script src=\"../js/jquery.min.js\"></script>\n");
      out.write("    <!-- Popper -->\n");
      out.write("    <script src=\"../js/popper.min.js\"></script>\n");
      out.write("    <!-- Bootstrap -->\n");
      out.write("    <script src=\"../js/bootstrap.min.js\"></script>\n");
      out.write("    <!-- All Plugins -->\n");
      out.write("    <script src=\"../js/roberto.bundle.js\"></script>\n");
      out.write("    <!-- Active -->\n");
      out.write("    <script src=\"../js/default-assets/active.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
